repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-ast
    -   id: check-yaml
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
    -   id: black-jupyter
        args: [--config=pyproject.toml]
-   repo: https://github.com/hadialqattan/pycln
    rev: v1.2.4
    hooks:
    -   id: pycln
        args: [--config=pyproject.toml]
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
    - id: clang-format
      args: [-i]
    - id: cppcheck
